name: "CI"
on:
  push:
    # Comment out this section to enable testing of all branches.
    branches:
      - master
  pull_request:
    paths-ignore: ['**.adoc']
    branches-ignore: ['future-doc']
jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/github-script@v3
        id: context
        with:
          script: console.log(JSON.stringify(context))
      - uses: actions/github-script@v3
        id: context2
        with:
          script: |
            let {repository, pull_request} = context.payload
            let branch = pull_request ? pull_request.head.ref : repository.default_branch
            let repo_full_name = pull_request ? pull_request.head.repository.full_name : repository.full_name
            console.log(`Checking branch ${branch} from ${repo_full_name}`)


